name: Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v21.02.01

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build RBF Loader
        run: |
          mkdir build && cd build && cmake ..
          cmake --build .
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: rbfloader
          path: build/